### PR TITLE
Fixes `wifi setup` (issue #375)

### LINKED ISSUE #375: particle serial wifi is broken on 1.23.0
@monkbroc , @m-mcgowan , @technobly 

```
$ particle serial wifi
? Should I scan for nearby Wi-Fi networks? Yes
? Select the Wi-Fi network with which you wish to connect your device: ROBINSON
? Should I try to auto-detect the wireless security type? Yes
> Detected WPA(PSK/TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) security
Attempting to configure Wi-Fi on /dev/cu.usbmodem1411
/usr/local/lib/node_modules/particle-cli/commands/SerialCommand.js:1231
				return cb(security + '\n', startTimeout.bind(self, 10000));
				       ^

TypeError: cb is not a function
    at parseSecurityType (/usr/local/lib/node_modules/particle-cli/commands/SerialCommand.js:1231:12)
    at SerialTrigger.serialDataCallback (/usr/local/lib/node_modules/particle-cli/oldlib/SerialTrigger.js:66:5)
    at emitOne (events.js:101:20)
    at SerialPort.emit (events.js:188:7)
    at whenBored (/usr/local/lib/node_modules/particle-cli/oldlib/SerialBoredParser.js:32:12)
    at Timeout._onTimeout (/usr/local/lib/node_modules/particle-cli/oldlib/SerialBoredParser.js:39:5)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

### PR DESCRIPTION
**Pull request by avtolstoy**
First argument was incorrectly being bound to `this`, when creating a partially applied `parseSecurityType` function.

Closes #375

### CODE REVIEW

**Comment by kennethlimcp** [comment]
Will we roll this out soon since `particle serial wifi` is an important feature?

**Comment by m-mcgowan** [comment]
I've approved the changes for expediency, but I would love to see unit tests that emulate 0.6.2 and 0.7.0 behaviours so we can be sure this code works as intended, and is backwards compatible.

**Comment by technobly** [comment]
For now I've manually tested that `particle serial wifi` works on 0.6.2 photon (WPA2 Personal) and 0.7.0-rc.1 photon (WPA2 Personal and WPA2 Enterprise).

One thing I've uncovered which I'm not certain is new behavior, is that when I answer NO to auto-detecting security type, sometimes I'm not presented with a prompt.

```
$ node particle.js serial wifi
? Should I scan for nearby Wi-Fi networks? Yes
? Select the Wi-Fi network with which you wish to connect your device: MYSSID
? Should I try to auto-detect the wireless security type? No
Attempting to configure Wi-Fi on /dev/cu.usbmodem141421
? Wi-Fi Password ************
```

This might not be a big deal with the JSON capabilities of the CLI now though.

I'm also wondering if the JSON method will work with WPA2 Enterprise... and how to specify certificates.   Hmm... @avtolstoy should that work?
