### ISSUE TITLE
Particle CLI cant load Firmware Binary - Electron

### ISSUE THREAD

**Issue by zoltan-fedor** [spark/particle-cli#224]
I have downloaded the binary, but cannot upload to Elektron.
Basically I have the same problem as here https://community.particle.io/t/particle-cli-cant-load-firmware-binary-electron-at-t-data-card-solved/205151, except reinstalling nodejs and particle cli does NOT solve the problem.

So I downloaded the firmware binary and trying to flash it to Elektron via USB using Linux Mint and particle cli.

```
myuser@laptop ~/Documents/Particle $ nodejs --version
v0.10.37
myuser@laptop ~/Documents/Particle $ particle --version
1.11.0
myuser@laptop ~/Documents/Particle $ particle identify
Your device id is myDeviceID
Your IMEI is myIMEI
Your ICCID is myICCID
Your system firmware version is 0.4.8
myuser@laptop ~/Documents/Particle $ particle flash --serial blink.bin
! PROTIP: Hold the SETUP button on your device until it blinks blue!
? Press ENTER when your device is blinking BLUE 
sending file: blink.bin

! serial: 
Error writing firmware...TypeError: Cannot call method 'copy' of undefined
TypeError: Cannot call method 'copy' of undefined
at Function.Buffer.concat (buffer.js:499:9)
at Object.YModem.sendPacket (/usr/lib/nodemodules/particle-cli/lib/ymodem.js:179:20)
at Object.YModem.sendFileHeader (/usr/lib/nodemodules/particle-cli/lib/ymodem.js:173:15)
at start (/usr/lib/node_modules/particle-cli/lib/ymodem.js:147:17)
at runTask (/usr/lib/node_modules/particle-cli/node_modules/when/pipeline.js:37:16)
at /usr/lib/node_modules/particle-cli/node_modules/when/pipeline.js:42:12
at tryCatchResolve (/usr/lib/node_modules/particle-cli/node_modules/when/lib/apply.js:46:23)
at callAndResolve (/usr/lib/node_modules/particle-cli/node_modules/when/lib/apply.js:30:12)
at callAndResolveNext (/usr/lib/node_modules/particle-cli/node_modules/when/lib/apply.js:40:4)
at tryCatchReject3 (/usr/lib/node_modules/particle-cli/node_modules/when/lib/makePromise.js:856:7)
```

What I am doing wrong?
What NodeJS / particle cli version am I supposed to be using?

After upgrade nodejs to v0.10.43, the latest in the 0.10.x series the issue is still there.

**Comment by zoltan-fedor** [comment]
After a few trials I finally succeeded with node v5.7.1;

$ particle flash --serial blink.bin
! PROTIP: Hold the SETUP button on your device until it blinks blue!
? Press ENTER when your device is blinking BLUE 
sending file: blink.bin

Flash success!
Aborted

**Comment by brycekahle** [comment]
Hmm, the node version definitely doesn't need to be that new. I'm going to reopen this for more investigation.

**Comment by zoltan-fedor** [comment]
Okey, I was surprised too, I thought it must be something else not the version, so it was a bit of a surprise that it was working with v5.7.1, specially as I have also tried v0.12.11 before and that hasn't worked either, so I was about to give up.

**Comment by ooniverse** [comment]
I'm encountering this same problem with my electron using nodejs=0.10.37-1chl1~utopic1.

but when I install nodejs 5.9.0 I get a different error:
```
 > sudo particle flash --serial firmware-binaries/blink.bin
Error loading command /usr/lib/node_modules/particle-cli/commands/SerialCommand.js Error: Cannot find module '/usr/lib/node_modules/particle-cli/node_modules/serialport/build/Release/node-v47-linux-x64/serialport.node'
/usr/lib/node_modules/particle-cli/commands/FlashCommand.js:146
		return serial.flashDevice.apply(serial, arguments);
		             ^

TypeError: Cannot read property 'flashDevice' of undefined
    at Object.extend.flashYModem (/usr/lib/node_modules/particle-cli/commands/FlashCommand.js:146:16)
    at Object.extend.flashSwitch (/usr/lib/node_modules/particle-cli/commands/FlashCommand.js:122:18)
    at Object.BaseCommand.runCommand (/usr/lib/node_modules/particle-cli/commands/BaseCommand.js:108:17)
    at Object.Interpreter.runCommand (/usr/lib/node_modules/particle-cli/lib/interpreter.js:93:13)
    at Object.Interpreter.handle (/usr/lib/node_modules/particle-cli/lib/interpreter.js:55:18)
    at Object.<anonymous> (/usr/lib/node_modules/particle-cli/bin/particle.js:20:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

```

I'll try installing nodejs v5.7.1 specifically.

BTW- I'm running Ubuntu 15.10.

**Comment by ooniverse** [comment]
With 5.7.1 I have the same problem:
```
> sudo particle flash --serial firmware-binaries/blink.bin
Error loading command /usr/lib/node_modules/particle-cli/commands/SerialCommand.js Error: Cannot find module '/usr/lib/node_modules/particle-cli/node_modules/serialport/build/Release/node-v47-linux-x64/serialport.node'
/usr/lib/node_modules/particle-cli/commands/FlashCommand.js:146
		return serial.flashDevice.apply(serial, arguments);
		             ^

TypeError: Cannot read property 'flashDevice' of undefined
    at Object.extend.flashYModem (/usr/lib/node_modules/particle-cli/commands/FlashCommand.js:146:16)
    at Object.extend.flashSwitch (/usr/lib/node_modules/particle-cli/commands/FlashCommand.js:122:18)
    at Object.BaseCommand.runCommand (/usr/lib/node_modules/particle-cli/commands/BaseCommand.js:108:17)
    at Object.Interpreter.runCommand (/usr/lib/node_modules/particle-cli/lib/interpreter.js:93:13)
    at Object.Interpreter.handle (/usr/lib/node_modules/particle-cli/lib/interpreter.js:55:18)
    at Object.<anonymous> (/usr/lib/node_modules/particle-cli/bin/particle.js:20:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

> node -v
v5.7.1

```

**Comment by ooniverse** [comment]
I updated particle-cli with:
`sudo npm install -g particle-cli`

and now I get:
```
> sudo particle flash --serial firmware-binaries/blink.bin
! PROTIP: Hold the SETUP button on your device until it blinks blue!
? Press ENTER when your device is blinking BLUE 
sending file: firmware-binaries/blink.bin

! serial: 
Error writing firmware...unknown message
undefined
```

**Comment by ooniverse** [comment]
Tried again after reset and it now works!

**Comment by brycekahle** [comment]
@ooniverse thanks for the additional data!

**Comment by ooniverse** [comment]
You're welcome.  Thanks for all the helpful support.  I wouldn't have been able to figure this out so quickly without all the useful pointers from previous posters.

**Comment by ooniverse** [comment]
I had already updated to the latest particle-cli before installing the new nodjs version.  

It must be order dependent . . . need to update particle-cli AFTER nodejs.

**Comment by brycekahle** [comment]
Yeah, looking at your error closely, it had trouble loading `node-serialport`
> Error loading command /usr/lib/node_modules/particle-cli/commands/SerialCommand.js Error: Cannot find module '/usr/lib/node_modules/particle-cli/node_modules/serialport/build/Release/node-v47-linux-x64/serialport.node'

If you updated node, but didn't reinstall then you would get that.

**Comment by sobellinni** [comment]
just installed node.js and particle cli, will not flash my electron through the usb serial, it does work over the air. 
in addition dfu-utill cannot find libusb-1.0.dll even though it is in the same folder.  flash -usb claims dfu-util was not installed even though it is also located in the windows/system32 folder

**Comment by kennethlimcp** [comment]
Can you try doing it over serial with particle flash --serial xxxxxx.bin?

ken
sent on mobile

On 29 Sep 2016 14:43, "sobellinni" <notifications@github.com> wrote:

just installed node.js and particle cli, will not flash my electron through
the usb serial, it does work over the air.
in addition dfu-utill cannot find libusb-1.0.dll even though it is in the
same folder. flash -usb claims dfu-util was not installed even though it is
also located in the windows/system32 folder

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/spark/particle-cli/issues/224#issuecomment-250383734>,
or mute the thread

**Comment by sobellinni** [comment]
It turns out that I tried it  with a binary generated by your PC tools - which tell me that the compilation is on line . This did not work, although the serial loader in the cli said it loaded.  The program that was put into the electron did not work. 

However, when I compiled the exact same code with the on line IDE , downloaded it to my computer and then loaded with the serial loader, it worked. Art Sobel 
Hardware Engineering 
Advanced RISC Technology

**Comment by monkbroc** [comment]
Could you please post more details of the steps you took that worked and the ones that did not work? We'll get to the bottom of this.

**Comment by sobellinni** [comment]
the .bin files are quite different  Art Sobel 
Hardware Engineering 
Advanced RISC Technology

**Comment by sobellinni** [comment]
I installed Node.js , Particle-cli, and Atom IDE  

I modified the  Blink program

Used the Cloud compile command after selecting my Electron device radio-ranger
Using the command  flash --serial  electron_program.bin

the response was success, but the Electron did not do anything 

Then I modified the same program in the on line IDE , compiled on the IDE and downloaded the file to the same directory


Using the command  flash --serial  program.bin

the response was success, and the program worked 
 

frustrated by this i also installed the dfu-util and libusb-1.0.dll 

  flash --usb  electron_program.bin could not  find dfu-util
dfu-util -1 could not  find libusb-1.0.dll even though it was in the same directory

**Comment by monkbroc** [comment]
Alright, this is enough information to dig into this. From your comment I see you are on Windows. I'll reproduce the steps you wrote up and I'll post back here.

**Comment by Jolley71717** [comment]
Did you have any luck? I'm having issues with this and can't seem to figure out how to fix it.

**Comment by sobellinni** [comment]
i got it to work 

after installing dfu-util 

but one of my CORE boards will not work with the particle app  .... 
 Art Sobel 
Hardware Engineering 
Advanced RISC Technology

**Comment by Jolley71717** [comment]
I deleted all of the npm installs and brew npm installs. I then downloaded npm version 7 and then downloaded the particle-cli straight from sparkfun using their curl command. It works again!!!!
